#!/bin/sh

HOST=0.0.0.0
PORT=80
WORKERS=1

#gunicorn -w 1 --max-requests 10 --timeout 300 --access-logfile - --error-logfile - -b 0.0.0.0:80 ambry_ui:app

exec gunicorn -w $WORKERS --max-requests 10 --timeout 300 \
--access-logfile - --error-logfile - \
-b $HOST:$PORT \
ambry_ui:app
